config/routes.rb
require 'sidekiq/web'

Myflix::Application.routes.draw do

  root to: 'videos#index'

  resources :videos, only: [:index, :show] do

    collection do
      get :search
    end

    member do
      post :review
    end
  end

  namespace :admin do
    resources :videos, only: [:new, :create]
    resources :payments, only: [:index]
  end

  resources :users, only: [:new, :create, :show]

  get 'users/new_invited/:token', to: 'users#new_invited', as: 'new_invited_user'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_out', to: 'sessions#destroy'

  get 'front', to: 'pages#front'
  get 'confirm_password_reset', to: 'pages#confirm_password_reset'
  get 'invalid_token', to: 'pages#invalid_token'

  get 'videos/category/:id', to: 'videos#category', as: :category

  get 'my_queue', to: 'queue_items#index'
  post 'update_queue', to: 'queue_items#update_queue'

  resources :queue_items, only: [:create, :destroy]

  get 'ui(/:action)', controller: 'ui'

  get 'people', to: 'relationships#index'

  resources :relationships, only: [:create, :destroy]

  # Must pluralise otherwise get _index in the path

  resources :forgot_passwords, only: [:new, :create]

  resources :reset_passwords, only: [:show, :create]

  resources :invitations, only: [:new, :create]

  mount Sidekiq::Web, at: '/sidekiq'

  mount StripeEvent::Engine => '/stripe_events'

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

  belongs_to :follower, class_name: 'User'

  belongs_to :leader, class_name: 'User'
  
  validates_uniqueness_of :follower, scope: [:follower_id, :leader_id]
  validates_uniqueness_of :leader,   scope: [:follower_id, :leader_id]

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController


  before_action :require_user

  def index
    @followings = current_user.following_rels
  end

  def create
    leading_user = User.find(params[:leader_id])

    Relationship.create(follower: current_user, leader: leading_user) if current_user.can_follow?leading_user

    redirect_to people_path
  end

  def destroy
    relationship = Relationship.find(params[:id])

    relationship.destroy if relationship && current_user == relationship.follower
    redirect_to people_path
  end
end

app/views/relationships/index.html.haml
%section.people
  %header
    %h2 People I Follow
  %table.table
    %thead
      %tr
        %th(width="30%")
        %th(width="20%") Videos in Queue
        %th(width="20%") Followers
        %th(width="30%") Unfollow
    %tbody
      - @followings.each do |following|
        %tr
          %td
            %img(src="http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(following.leader.email_address.downcase)}?s=40")
            = link_to following.leader.full_name, following.leader
          %td.extra-padding= following.leader.queue_items.count
          %td.extra-padding= following.leader.leading_rels.count
          %td.extra-padding
            = link_to relationship_path(following), method: :delete do
              %i.glyphicon.glyphicon-remove