config/routes.rb
require 'sidekiq/web'

Myflix::Application.routes.draw do

  root to: 'videos#index'

  resources :videos, only: [:index, :show] do

    collection do
      get :search
    end

    member do
      post :review
    end
  end

  namespace :admin do
    resources :videos, only: [:new, :create]
    resources :payments, only: [:index]
  end

  resources :users, only: [:new, :create, :show]

  get 'users/new_invited/:token', to: 'users#new_invited', as: 'new_invited_user'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_out', to: 'sessions#destroy'

  get 'front', to: 'pages#front'
  get 'confirm_password_reset', to: 'pages#confirm_password_reset'
  get 'invalid_token', to: 'pages#invalid_token'

  get 'videos/category/:id', to: 'videos#category', as: :category

  get 'my_queue', to: 'queue_items#index'
  post 'update_queue', to: 'queue_items#update_queue'

  resources :queue_items, only: [:create, :destroy]

  get 'ui(/:action)', controller: 'ui'

  get 'people', to: 'relationships#index'

  resources :relationships, only: [:create, :destroy]

  # Must pluralise otherwise get _index in the path

  resources :forgot_passwords, only: [:new, :create]

  resources :reset_passwords, only: [:show, :create]

  resources :invitations, only: [:new, :create]

  mount Sidekiq::Web, at: '/sidekiq'

  mount StripeEvent::Engine => '/stripe_events'

end

app/models/video.rb
include ActionView::Helpers::NumberHelper

class Video < ActiveRecord::Base

  belongs_to :category

  # validates :title, presence: true
    
  # validates :description, presence: true

  # Use short hand instaed

  mount_uploader :large_cover, LargeCoverUploader
  mount_uploader :small_cover, SmallCoverUploader

  has_many :reviews,  -> { order 'created_at DESC'}, as: :reviewable

  has_many :queue_items

  validates_presence_of :title, :description

  def self.search_by_title(search_term)

    return [] if search_term.blank?

    where('title LIKE ?', "%#{search_term}%").order('created_at DESC')

  end

  def average_rating

    total = 0.0
    size = 0

    reviews.find_each do |review|
      if review.rating
        total += review.rating 
        size += 1 # There is no pre or post increment operator in Ruby
      end
    end

    return nil if size == 0

    average = number_with_precision(total / size, precision: 1)

  end

end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < AdminsController

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)

    if @video.save
      flash[:success] = "Video #{@video.title} successfully added."
      redirect_to new_admin_video_path
    else
      flash[:danger] = 'There was an error adding that video, please see details below.'
      render :new
    end

  end

  private

  def video_params
    params.require(:video).permit(:title, :category_id, :description, :large_cover, :small_cover, "video_url")
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  before_filter :require_user
  before_action :set_video, only: [:review, :show]


  def index
    @categories = Category.all
  end

  def category
     @category = Category.find(params[:id])
  end

  def show
    @review = Review.new
  end

  def search
    @search_term = params[:search_term]
    @videos = Video.search_by_title(@search_term)
  end

  def review

    new_review = Review.new(rating: review_params[:rating], comment: review_params[:comment], 
                            user: current_user, reviewable: @video)

    new_review.save ? @review = Review.new : @review = new_review

    render :show

  end

  def set_video
      @video = VideoDecorator.new(Video.find(params[:id]))
  end

  def review_params
    params.require(:review).permit(:comment, :rating) 
  end

end

app/views/videos/category.html.haml
%article.video_category
  %header
    %h3= link_to @category.name, @category
  .videos.row
    - @category.videos.each do |video|
      .video.col-sm-2
        = link_to "", nil do
          %img(src="#{video.small_cover}")

app/views/videos/index.html.haml
- @categories.each do |category|
  %article.video_category
    %header
      %h3= link_to category.name, category
    .videos.row
      - category.recent_videos.each do |video|
        .video.col-sm-2
          = link_to video, nil do
            %img(src="#{video.small_cover}")

app/views/videos/search.html.haml
%article.video_category
  %header
    %h3= "Results for videos searched by: #{@search_term}"
  .videos.row
    - @videos.each do |video|
      .video.col-sm-2
        = link_to video, nil do
          %img(src="#{video.small_cover}")

app/views/videos/show.html.haml
%article.video
  .container
    .row
      .video_large_cover.col-sm-7.col-sm-offset-1
        %img(src="#{@video.large_cover}")
      .video_info.col-sm-3
        %header
          %h3= @video.title
          %span Rating: #{@video.rating}
        %p= @video.description
        .actions
          %a.btn.btn-primary(href="#{@video.video_url}") Watch Now
          = link_to '+ My Queue', queue_items_path(video_id: @video.id), method: :post, class: 'btn btn-default' unless video_in_my_queue?(@video)

%section.reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      = bootstrap_form_for @review, url: review_video_path(@video) do |f|
        %fieldset
          .form-group
            .row
              .col-sm-3
                = f.select :rating, options_for_video_rating, label: 'Rate this video', class: 'form-control'
          .form-group
            .row
              .col-sm-8
                = f.text_area :comment, label: 'Write Review', rows: 6, class: 'form-control'
        %fieldset.form-group.actions.clearfix
          = f.submit 'Submit', class: 'btn'
          = link_to 'Cancel', video_path(@video)
      %header
        %h3 User Reviews (#{@video.reviews.count})
      %ul
        - @video.reviews.each do |rev|
          %article.review
            %li.row
              .col-sm-2
                %span Rating: #{rev.rating}/5
                %p by #{link_to rev.user.full_name, rev.user}
              .col-sm-8
                %p= rev.comment