config/routes.rb
require 'sidekiq/web'

Myflix::Application.routes.draw do

  root to: 'videos#index'

  resources :videos, only: [:index, :show] do

    collection do
      get :search
    end

    member do
      post :review
    end
  end

  namespace :admin do
    resources :videos, only: [:new, :create]
    resources :payments, only: [:index]
  end

  resources :users, only: [:new, :create, :show]

  get 'users/new_invited/:token', to: 'users#new_invited', as: 'new_invited_user'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_out', to: 'sessions#destroy'

  get 'front', to: 'pages#front'
  get 'confirm_password_reset', to: 'pages#confirm_password_reset'
  get 'invalid_token', to: 'pages#invalid_token'

  get 'videos/category/:id', to: 'videos#category', as: :category

  get 'my_queue', to: 'queue_items#index'
  post 'update_queue', to: 'queue_items#update_queue'

  resources :queue_items, only: [:create, :destroy]

  get 'ui(/:action)', controller: 'ui'

  get 'people', to: 'relationships#index'

  resources :relationships, only: [:create, :destroy]

  # Must pluralise otherwise get _index in the path

  resources :forgot_passwords, only: [:new, :create]

  resources :reset_passwords, only: [:show, :create]

  resources :invitations, only: [:new, :create]

  mount Sidekiq::Web, at: '/sidekiq'

  mount StripeEvent::Engine => '/stripe_events'

end

app/views/shared/_header.html.haml
%section#top-header.row
  %h1.col-md-2
    = link_to "MyFLiX"
  - if current_user
    %ul.col-md-4.clearfix
      %li= link_to "Videos", videos_path
      %li= link_to "My Queue", my_queue_path
      %li= link_to "People", people_path
    %form.col-md-5.navbar-form(action="#{search_videos_path}" method="get")
      .form-group
        %input.form-control(name="search_term" type="text" placeholder="Search for videos here")
      %button.btn.btn-default(type="submit") Search
    #user_links.pull-right
      %ul
        %li.dropdown
          %a(href="#" id="dlabel" role="button" data-toggle="dropdown" class="dropdown-toggle" data-target="#")
            Welcome, "#{current_user.full_name}"
            %b.caret
          %ul.dropdown-menu(role="menu" aria-labelledby="dlabel")
            %li
              = link_to "Invite a Friend", new_invitation_path
              %a(href="#") Account
              %a(href="#") Plan and Billing
              - if current_user.admin
                %a= link_to "View User Payments (*Admin)", admin_payments_path
                %a= link_to "Create New Video (*Admin)", new_admin_video_path
              %a= link_to "Sign Out", sign_out_path

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)