config/routes.rb
require 'sidekiq/web'

Myflix::Application.routes.draw do

  root to: 'videos#index'

  resources :videos, only: [:index, :show] do

    collection do
      get :search
    end

    member do
      post :review
    end
  end

  namespace :admin do
    resources :videos, only: [:new, :create]
    resources :payments, only: [:index]
  end

  resources :users, only: [:new, :create, :show]

  get 'users/new_invited/:token', to: 'users#new_invited', as: 'new_invited_user'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_out', to: 'sessions#destroy'

  get 'front', to: 'pages#front'
  get 'confirm_password_reset', to: 'pages#confirm_password_reset'
  get 'invalid_token', to: 'pages#invalid_token'

  get 'videos/category/:id', to: 'videos#category', as: :category

  get 'my_queue', to: 'queue_items#index'
  post 'update_queue', to: 'queue_items#update_queue'

  resources :queue_items, only: [:create, :destroy]

  get 'ui(/:action)', controller: 'ui'

  get 'people', to: 'relationships#index'

  resources :relationships, only: [:create, :destroy]

  # Must pluralise otherwise get _index in the path

  resources :forgot_passwords, only: [:new, :create]

  resources :reset_passwords, only: [:show, :create]

  resources :invitations, only: [:new, :create]

  mount Sidekiq::Web, at: '/sidekiq'

  mount StripeEvent::Engine => '/stripe_events'

end

app/controllers/reset_passwords_controller.rb
class ResetPasswordsController < ApplicationController

  def show

    user = User.find_by(token: params[:id])

    if user
      @token = params[:id]
    else
      redirect_to invalid_token_path 
    end

  end


  def create
    user = User.find_by(token: params[:token])

    if user
      user.password = params[:password]
      user.password_confirmation = params[:password_confirmation]
      user.generate_token

      if user.save
        redirect_to sign_in_path, notice: 'Your password has been reset. Please sign in'
      else
        @token = params[:token]
        flash[:danger] = user.errors.full_messages.join('. ')
        render :show
      end

    else
      redirect_to invalid_token_path 
    end
    
  end

end

app/views/reset_passwords/show.html.haml
%section.reset_password.container
  .row
    .col-sm-10.col-sm-offset-1
      = form_tag reset_passwords_path do
        %header
          %h1 Reset Your Password
        %fieldset.form-group
          .row
            .col-sm-4
              = label_tag 'New Password'
              = password_field_tag :password, nil, class: 'form-control'
              = hidden_field_tag :token, @token
          %br
          .row
            .col-sm-4
              = label_tag 'Confirm Password'
              = password_field_tag :password_confirmation, nil, class: 'form-control'
        %fieldset.form-group.action
          %input(type="submit" value="Reset Password" class="btn btn-default")